# Generated by Django 4.2 on 2024-06-19 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memeshub', '0002_recentsearch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentsearch',
            name='search_term',
            field=models.CharField(max_length=50),
        ),
    ]
